### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by jacobspring** [Padnezz/kahoot-hack-mod#1]
it possibly to port this over to windows?

**Comment by Padnezz** [comment]
Yes it is, I will sometime this week or next week add instructions for
Windows, hang tight :)
Den 7 okt 2015 17:52 skrev "jacobspring" <notifications@github.com>:

**Comment by jacobspring** [comment]
Like Ik I could run Mac in a vitural machine, but my plan was to leave my computer on at home and connect with team viewer when I need to mess with the teacher, since it is not a laptop.

But I would prefer not since I do not have that much ram in that computer, and it would make it very very slow

**Comment by Padnezz** [comment]
Ah okay, I understand. I will not be responsible if you get shit heheheh.
But if you want I can try to fix it in the next idk 6 hours?
Den 7 okt 2015 18:01 skrev "jacobspring" <notifications@github.com>:

**Comment by jacobspring** [comment]
My teachers aren't the brightest so I don't got anything to worry about, more of flood the room and possibly get all the answers correct fast so I can get bonus points or something... Or even if I am doing horrible, use the Crash game option...

I realize that dose not make sense I just typed what popped in  my head at the time, but I will be keeping an eye out for it! Idk how much help I will be, but if it is something stupid easy just let me know =D

**Comment by Padnezz** [comment]
Hello, I really can't do anything today with the Windows thing. But if you
know something about computers and programming, you could always help me!
(Of course you will get credit)

You could actually make "Go" work on Windows so I know what to write, then
we can take it from there
Den 7 okt 2015 18:44 skrev "jacobspring" <notifications@github.com>:

**Comment by jacobspring** [comment]
I thought the go language also worked on windows, I just have no clue how to run it since their is Mac only instructions

**Comment by Padnezz** [comment]
Hello, check the second latest commit :)

**Comment by Padnezz** [comment]
Or yeah, commit 5d7a675
